version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: web
    container_name: bipas_web
    restart: unless-stopped
    ports:
     - 11521:5001
    depends_on:
      - redis
    volumes: ['./api:/api']
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    hostname: worker
    container_name: bipas_worker
    restart: unless-stopped
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue']
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    hostname: monitor
    container_name: bipas_monitor
    restart: unless-stopped
    ports:
     - 11523:5555
    command:  ['celery', 'flower', '-A', 'tasks']
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
      - worker
    volumes: ['./celery-queue:/queue']
  redis:
    image: redis:alpine
    container_name: bipas_redis
    hostname: redis
    restart: unless-stopped
    volumes:
    - ./data/redis:/data
    ports:
      - 11522:6379
